language: go

os: [linux, osx]

osx_image: mavericks

before_install:
    - echo $GOPATH
    - echo $GOROOT
    - sudo apt-get install tree

install:
    - go get -u github.com/oliveagle/jsonpath

script:
   #  debug gopath
   - tree -d $GOPATH
   - tree -L 1 /proc 
   - cd $GOPATH/src/github.com/oliveagle/jsonpath
   # test script
   - go test . -v